# Generated by Django 4.2.3 on 2023-07-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snipped',
            field=models.CharField(default='click link to read...', max_length=225),
        ),
    ]
